{"name": "test_case_catch_no_exception", "status": "failed", "statusDetails": {"message": "Failed: DID NOT RAISE <class 'ZeroDivisionError'>", "trace": "normal_fixture = None\n\n    def test_case_catch_no_exception(normal_fixture):\n        with pytest.raises(ZeroDivisionError):\n            assert 1/1\n>           logging.info(\"test_case_catch_no_exception\")\nE           Failed: DID NOT RAISE <class 'ZeroDivisionError'>\n\ntest_exception.py:28: Failed"}, "attachments": [{"name": "log", "source": "2eb219c8-5a50-4927-a06a-57bf096759c9-attachment.txt", "type": "text/plain"}], "start": 1627199677991, "stop": 1627199677992, "uuid": "775905d4-a040-4da4-8486-b26d2acc9753", "historyId": "5c2a1700651646ee0260b141c4103900", "testCaseId": "efdaa9090de4ea8c5c9462ea66c2563d", "fullName": "test_exception#test_case_catch_no_exception", "labels": [{"name": "suite", "value": "test_exception"}, {"name": "host", "value": "ccyangdeMacBook-Pro.local"}, {"name": "thread", "value": "58486-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_exception"}]}