{"name": "test_fixture_exception", "status": "broken", "statusDetails": {"message": "Exception: exception", "trace": "@pytest.fixture()\n    def exception_fixture():\n        logging.info(\"exception_fixture setup\")\n>       raise Exception(\"exception\")\nE       Exception: exception\n\ntest_exception.py:14: Exception"}, "attachments": [{"name": "log", "source": "e503edb5-42f2-4b2a-b1f0-fdef0747df56-attachment.txt", "type": "text/plain"}], "start": 1627199391476, "stop": 1627199391476, "uuid": "2caddeca-8dbf-4914-b778-9ad94a23ca27", "historyId": "cac4bef9a8e9aa137ec5e0259dda4c61", "testCaseId": "e5ca0258b912f817b4bb5dda18b16edf", "fullName": "test_exception#test_fixture_exception", "labels": [{"name": "suite", "value": "test_exception"}, {"name": "host", "value": "ccyangdeMacBook-Pro.local"}, {"name": "thread", "value": "58268-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_exception"}]}