{"name": "test_case_catch_no_exception", "status": "failed", "statusDetails": {"message": "Failed: DID NOT RAISE <class 'ZeroDivisionError'>", "trace": "normal_fixture = None\n\n    def test_case_catch_no_exception(normal_fixture):\n        with pytest.raises(ZeroDivisionError):\n            logging.info(\"test_case_catch_no_exception\")\n>           assert 1/1\nE           Failed: DID NOT RAISE <class 'ZeroDivisionError'>\n\ntest_exception.py:28: Failed"}, "attachments": [{"name": "log", "source": "15f2b7b9-4925-4510-85d8-723a19d52989-attachment.txt", "type": "text/plain"}], "start": 1627199625085, "stop": 1627199625085, "uuid": "b08b4dc8-22e1-422c-a032-f9245e582092", "historyId": "5c2a1700651646ee0260b141c4103900", "testCaseId": "efdaa9090de4ea8c5c9462ea66c2563d", "fullName": "test_exception#test_case_catch_no_exception", "labels": [{"name": "suite", "value": "test_exception"}, {"name": "host", "value": "ccyangdeMacBook-Pro.local"}, {"name": "thread", "value": "58448-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_exception"}]}