{"name": "test_fixture_exception", "status": "broken", "statusDetails": {"message": "Exception: exception", "trace": "@pytest.fixture()\n    def exception_fixture():\n        logging.info(\"exception_fixture setup\")\n>       raise Exception(\"exception\")\nE       Exception: exception\n\ntest_exception.py:14: Exception"}, "attachments": [{"name": "log", "source": "ef94cc3f-3a82-4296-a506-f5ed63928796-attachment.txt", "type": "text/plain"}], "start": 1627199678109, "stop": 1627199678109, "uuid": "500c70a0-cee0-42f9-9368-ea1fbaf38c8e", "historyId": "cac4bef9a8e9aa137ec5e0259dda4c61", "testCaseId": "e5ca0258b912f817b4bb5dda18b16edf", "fullName": "test_exception#test_fixture_exception", "labels": [{"name": "suite", "value": "test_exception"}, {"name": "host", "value": "ccyangdeMacBook-Pro.local"}, {"name": "thread", "value": "58486-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_exception"}]}