{"name": "test_fixture_exception", "status": "broken", "statusDetails": {"message": "Exception: exception", "trace": "@pytest.fixture()\n    def exception_fixture():\n        logging.info(\"exception_fixture setup\")\n>       raise Exception(\"exception\")\nE       Exception: exception\n\ntest_exception.py:14: Exception"}, "attachments": [{"name": "log", "source": "a4b9a282-0193-420d-b8d4-04beb269457a-attachment.txt", "type": "text/plain"}], "start": 1627199625186, "stop": 1627199625186, "uuid": "b05af528-61d0-4935-b089-9d0087ff04bf", "historyId": "cac4bef9a8e9aa137ec5e0259dda4c61", "testCaseId": "e5ca0258b912f817b4bb5dda18b16edf", "fullName": "test_exception#test_fixture_exception", "labels": [{"name": "suite", "value": "test_exception"}, {"name": "host", "value": "ccyangdeMacBook-Pro.local"}, {"name": "thread", "value": "58448-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_exception"}]}