{"name": "test_fixture_exception", "status": "broken", "statusDetails": {"message": "Exception: exception", "trace": "@pytest.fixture()\n    def exception_fixture():\n        logging.info(\"exception_fixture setup\")\n>       raise Exception(\"exception\")\nE       Exception: exception\n\ntest_exception.py:14: Exception"}, "attachments": [{"name": "log", "source": "5ef30cff-4be2-486b-b0cc-5831322f9a0d-attachment.txt", "type": "text/plain"}], "start": 1627199571345, "stop": 1627199571345, "uuid": "b263e4f6-d30e-4b89-9441-3062f8c9ec17", "historyId": "cac4bef9a8e9aa137ec5e0259dda4c61", "testCaseId": "e5ca0258b912f817b4bb5dda18b16edf", "fullName": "test_exception#test_fixture_exception", "labels": [{"name": "suite", "value": "test_exception"}, {"name": "host", "value": "ccyangdeMacBook-Pro.local"}, {"name": "thread", "value": "58394-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_exception"}]}